/**
 * Minimal ustar (POSIX.1-1988) writer and reader for checkpoint bundles (SPEC-011 `bundleFile`).
 *
 * In-repo rather than a dependency: a bundle only holds regular files with short, generated names, so a
 * full tar implementation would add surface without adding anything a bundle needs.
 *
 * Writer: every entry is a regular file with mode 0600, uid/gid 0, mtime 0 and no user or group names,
 * so identical inputs produce identical bytes. Entries are streamed to a file handle one at a time, so
 * the bundle as a whole never has to fit in memory.
 *
 * Reader: built for untrusted input (a bundle handed over from another machine). It verifies every
 * header checksum, accepts only regular files, requires the end-of-archive marker, and rejects absolute
 * names, empty / `.` / `..` segments, backslashes, non-printable bytes and duplicate names. So no entry
 * name can address anything outside the bundle's own namespace, and a truncated file is never mistaken
 * for a complete one.
 */
import type { FileHandle } from 'node:fs/promises';

const BLOCK = 512;
const NAME_MAX = 100;
const PREFIX_MAX = 155;
/** The size field holds 11 octal digits. */
const MAX_ENTRY_SIZE = 8 ** 11 - 1;
const ENTRY_MODE = 0o600;
const MAGIC = 'ustar\0';
const VERSION = '00';
const TYPE_FILE = 0x30; // '0'
const TYPE_FILE_OLD = 0x00; // pre-POSIX regular file

/** A bundle file that is not a well-formed, safe tar archive. */
export class BundleFormatError extends Error {
  override readonly name = 'BundleFormatError';
}

/** Entry names are generated by the bundle code: printable ASCII, `/`-separated, relative, canonical. */
const ENTRY_NAME = /^[\x21-\x5b\x5d-\x7e]+$/;

/** Why `name` is not an acceptable entry name, or null when it is. */
export function entryNameProblem(name: string): string | null {
  if (!ENTRY_NAME.test(name)) return 'must be non-empty printable ASCII without spaces or backslashes';
  if (name.startsWith('/')) return 'must be relative';
  for (const segment of name.split('/')) {
    if (segment === '' || segment === '.' || segment === '..') return 'must not contain empty, "." or ".." segments';
  }
  return null;
}

function assertEntryName(name: string): void {
  const problem = entryNameProblem(name);
  if (problem !== null) throw new BundleFormatError(`tar entry name ${JSON.stringify(name)} ${problem}`);
}

function writeOctal(header: Buffer, offset: number, width: number, value: number): void {
  const digits = value.toString(8).padStart(width - 1, '0');
  if (digits.length > width - 1) throw new BundleFormatError(`value ${value} does not fit a ${width}-byte tar field`);
  header.write(digits, offset, width - 1, 'ascii');
  header[offset + width - 1] = 0;
}

function checksumOf(header: Uint8Array): number {
  let sum = 0;
  for (let i = 0; i < BLOCK; i++) sum += i >= 148 && i < 156 ? 0x20 : header[i]!;
  return sum;
}

/** Split a name over the ustar `prefix` and `name` fields. */
function splitName(name: string): { name: string; prefix: string } {
  if (name.length <= NAME_MAX) return { name, prefix: '' };
  for (let slash = name.lastIndexOf('/'); slash > 0; slash = name.lastIndexOf('/', slash - 1)) {
    const prefix = name.slice(0, slash);
    const rest = name.slice(slash + 1);
    if (rest.length > NAME_MAX) break;
    if (prefix.length <= PREFIX_MAX) return { name: rest, prefix };
  }
  throw new BundleFormatError(`tar entry name ${JSON.stringify(name)} is too long for ustar`);
}

function encodeHeader(name: string, size: number): Buffer {
  const header = Buffer.alloc(BLOCK);
  const parts = splitName(name);
  header.write(parts.name, 0, NAME_MAX, 'ascii');
  writeOctal(header, 100, 8, ENTRY_MODE);
  writeOctal(header, 108, 8, 0);
  writeOctal(header, 116, 8, 0);
  writeOctal(header, 124, 12, size);
  writeOctal(header, 136, 12, 0);
  header[156] = TYPE_FILE;
  header.write(MAGIC, 257, 6, 'ascii');
  header.write(VERSION, 263, 2, 'ascii');
  header.write(parts.prefix, 345, PREFIX_MAX, 'ascii');
  // Checksum: 6 octal digits, NUL, space.
  header.write(checksumOf(header).toString(8).padStart(6, '0'), 148, 6, 'ascii');
  header[154] = 0;
  header[155] = 0x20;
  return header;
}

function padding(size: number): number {
  return (BLOCK - (size % BLOCK)) % BLOCK;
}

async function writeFully(handle: FileHandle, bytes: Uint8Array, position: number): Promise<void> {
  let offset = 0;
  while (offset < bytes.byteLength) {
    const { bytesWritten } = await handle.write(bytes, offset, bytes.byteLength - offset, position + offset);
    offset += bytesWritten;
  }
}

/** Streams tar entries to an open file handle, starting at position 0. */
export class TarWriter {
  readonly #handle: FileHandle;
  readonly #names = new Set<string>();
  #position = 0;
  #finished = false;

  constructor(handle: FileHandle) {
    this.#handle = handle;
  }

  /** Bytes written so far. */
  get size(): number {
    return this.#position;
  }

  async add(name: string, data: Uint8Array): Promise<void> {
    if (this.#finished) throw new BundleFormatError('tar archive is already finished');
    assertEntryName(name);
    if (this.#names.has(name)) throw new BundleFormatError(`duplicate tar entry ${JSON.stringify(name)}`);
    if (data.byteLength > MAX_ENTRY_SIZE) throw new BundleFormatError(`tar entry ${JSON.stringify(name)} is too large`);
    this.#names.add(name);
    const header = encodeHeader(name, data.byteLength);
    await writeFully(this.#handle, header, this.#position);
    this.#position += BLOCK;
    await writeFully(this.#handle, data, this.#position);
    this.#position += data.byteLength;
    const pad = padding(data.byteLength);
    if (pad > 0) {
      await writeFully(this.#handle, Buffer.alloc(pad), this.#position);
      this.#position += pad;
    }
  }

  /** Write the end-of-archive marker (two zero blocks). */
  async finish(): Promise<void> {
    if (this.#finished) return;
    this.#finished = true;
    await writeFully(this.#handle, Buffer.alloc(2 * BLOCK), this.#position);
    this.#position += 2 * BLOCK;
  }
}

export interface TarEntry {
  readonly name: string;
  readonly size: number;
  /** Absolute file offset of the entry's first content byte. */
  readonly offset: number;
}

function readField(header: Buffer, offset: number, width: number): string {
  const raw = header.subarray(offset, offset + width);
  const nul = raw.indexOf(0);
  return raw.subarray(0, nul === -1 ? width : nul).toString('latin1');
}

function parseOctal(header: Buffer, offset: number, width: number, what: string): number {
  const text = readField(header, offset, width).trim();
  if (!/^[0-7]+$/.test(text)) throw new BundleFormatError(`tar header has a malformed ${what} field`);
  return parseInt(text, 8);
}

function isZeroBlock(block: Buffer): boolean {
  for (const byte of block) if (byte !== 0) return false;
  return true;
}

async function readExactly(handle: FileHandle, length: number, position: number): Promise<Buffer> {
  const buffer = Buffer.alloc(length);
  let offset = 0;
  while (offset < length) {
    const { bytesRead } = await handle.read(buffer, offset, length - offset, position + offset);
    if (bytesRead === 0) throw new BundleFormatError('tar archive is truncated');
    offset += bytesRead;
  }
  return buffer;
}

/** Index every entry of the archive (headers only; content is read on demand with readTarEntry). */
export async function readTarIndex(handle: FileHandle): Promise<TarEntry[]> {
  const fileSize = (await handle.stat()).size;
  const entries: TarEntry[] = [];
  const names = new Set<string>();
  let position = 0;
  for (;;) {
    if (position + BLOCK > fileSize) throw new BundleFormatError('tar archive is truncated (no end-of-archive marker)');
    const header = await readExactly(handle, BLOCK, position);
    if (isZeroBlock(header)) {
      if (position + 2 * BLOCK > fileSize || !isZeroBlock(await readExactly(handle, BLOCK, position + BLOCK))) {
        throw new BundleFormatError('tar archive has a malformed end-of-archive marker');
      }
      return entries;
    }
    if (parseOctal(header, 148, 8, 'checksum') !== checksumOf(header)) {
      throw new BundleFormatError(`tar header at byte ${position} fails its checksum`);
    }
    if (readField(header, 257, 6) !== 'ustar' || header.toString('latin1', 263, 265) !== VERSION) {
      throw new BundleFormatError(`tar header at byte ${position} is not ustar`);
    }
    const type = header[156];
    if (type !== TYPE_FILE && type !== TYPE_FILE_OLD) {
      throw new BundleFormatError(`tar entry at byte ${position} is not a regular file (type ${JSON.stringify(String.fromCharCode(type ?? 0))})`);
    }
    const prefix = readField(header, 345, PREFIX_MAX);
    const shortName = readField(header, 0, NAME_MAX);
    const name = prefix === '' ? shortName : `${prefix}/${shortName}`;
    assertEntryName(name);
    if (names.has(name)) throw new BundleFormatError(`duplicate tar entry ${JSON.stringify(name)}`);
    names.add(name);
    const size = parseOctal(header, 124, 12, 'size');
    const offset = position + BLOCK;
    if (offset + size > fileSize) throw new BundleFormatError(`tar entry ${JSON.stringify(name)} is truncated`);
    entries.push({ name, size, offset });
    position = offset + size + padding(size);
  }
}

/** The content bytes of one indexed entry. */
export function readTarEntry(handle: FileHandle, entry: TarEntry): Promise<Buffer> {
  return readExactly(handle, entry.size, entry.offset);
}
