/**
 * Distillation prompt (SPEC-007 "Input bounding"). Built from the state object and the ledger events of
 * `ledgerRange` only, never the full run.
 *
 * Redaction (SPEC-003): everything that came from a capture goes through sanitize() before it enters the
 * prompt. That covers every string key and value of every event payload, inline or read from its CAS
 * blob, and the pending-intent ids of the state object. Structural identifiers are NOT sanitized: event
 * ids, seq, type, actor, checkpoint ids, the commit and blob hashes. They are generated by ckpt, not
 * captured, and the model must be able to cite them. The high-entropy detector would otherwise erase
 * exactly those ids.
 */
import { canonicalJSON } from '../ledger/canonical-json.js';
import type { AgentStateObject } from '../model/types.js';
import { sanitize } from '../redact/index.js';
import { DISTILLED_FIELDS, PROMPT_VERSION, type DistillEvent, type DistillRequest } from './types.js';

/** An event of the range with its payload resolved: the inline payload, or its CAS blob's content. */
export interface PromptEvent {
  readonly event_id: string;
  readonly seq: number;
  readonly type: string;
  readonly actor: string;
  readonly ts?: string;
  /** Parsed JSON, or the blob's text when it is not JSON. Redacted by buildPrompt. */
  readonly payload: unknown;
  /** sha256 of the CAS blob the payload was read from, or null for an inline payload. */
  readonly payload_ref: string | null;
}

export interface PromptInput {
  readonly request: DistillRequest;
  readonly state: AgentStateObject;
  /** The events of the range, in seq order. */
  readonly events: readonly PromptEvent[];
  /** The artifact hashes a claim may cite. */
  readonly artifactRefs: readonly string[];
}

/** The events with previous cursor < seq <= cursor, in seq order. */
export function eventsInRange<T extends Pick<DistillEvent, 'seq'>>(events: readonly T[], range: readonly [number, number]): T[] {
  const [from, to] = range;
  return events.filter((event) => event.seq > from && event.seq <= to).sort((a, b) => a.seq - b.seq);
}

/** A copy of a JSON value with every string key and value passed through sanitize(). */
export function redactJson(value: unknown): unknown {
  if (typeof value === 'string') return sanitize(value).output;
  if (Array.isArray(value)) return value.map(redactJson);
  if (typeof value === 'object' && value !== null) {
    // fromEntries defines own properties, so a `__proto__` key stays data.
    return Object.fromEntries(Object.entries(value).map(([key, child]) => [sanitize(key).output, redactJson(child)]));
  }
  return value;
}

const INSTRUCTIONS = [
  `ckpt distiller, prompt ${PROMPT_VERSION}.`,
  'You are reading one checkpoint of an AI agent run: its deterministic state object and the ledger events recorded since the previous checkpoint.',
  'Infer the semantic state of the run at this checkpoint. Everything you return is interpretation, not fact, and must cite its evidence.',
  '',
  'Reply with one JSON object and nothing else:',
  '{"claims":[{"field":"<field>","value":"<text>","confidence":0.8,"provenance":{"event_ids":[],"artifact_refs":[],"workspace_paths":[],"checkpoint_ids":[]}}]}',
  '',
  'Rules:',
  `- field is one of: ${DISTILLED_FIELDS.join(', ')}. confidence is optional, between 0 and 1.`,
  '- provenance must cite at least one piece of evidence.',
  '- event_ids may only name events listed under LEDGER. artifact_refs may only name hashes listed under ARTIFACTS.',
  '- checkpoint_ids may only name checkpoints of this run. workspace_paths are repo-relative paths.',
  '- A claim that breaks a rule is discarded. Leave a claim out rather than guess its evidence.',
  '- Text shown as [REDACTED:<kind>] was removed for security. Never try to reconstruct it.',
].join('\n');

export function buildPrompt(input: PromptInput): string {
  const { request, state, events, artifactRefs } = input;
  const [from, to] = request.ledgerRange;
  const stateView = {
    ...state,
    pending_intent: state.pending_intent.map((intent) => ({
      ...intent,
      intent_id: intent.intent_id === null ? null : sanitize(intent.intent_id).output,
    })),
  };
  const lines = events.map((event) =>
    canonicalJSON({
      event_id: event.event_id,
      seq: event.seq,
      type: event.type,
      actor: event.actor,
      ...(event.ts === undefined ? {} : { ts: event.ts }),
      payload: redactJson(event.payload),
      payload_ref: event.payload_ref,
    }),
  );
  return [
    INSTRUCTIONS,
    '',
    'CHECKPOINT',
    canonicalJSON({ checkpointId: request.checkpointId, ledgerRange: [from, to], workspaceCommit: request.workspaceCommit }),
    '',
    'STATE',
    canonicalJSON(stateView),
    '',
    'ARTIFACTS',
    canonicalJSON([...artifactRefs]),
    '',
    `LEDGER (${events.length} events, seq ${from + 1}..${to})`,
    ...lines,
    '',
  ].join('\n');
}
